name: 'update profile'

on:
  schedule:
    - cron: '*/5 * * * *'

permissions:
  contents: read

jobs:
  profile:
    name: 'generate profile contents'
    runs-on: 'ubuntu-latest'
    permissions:
      contents: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2 # v2.3.0
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            github.com:443
            nodejs.org:443
            raw.githubusercontent.com:443
            registry.npmjs.org:443
      - uses: actions/checkout@v4
      - uses: ljharb/actions/node/install@main
        with:
          skip-install: true
      - run: npm install
        working-directory: ./profile
      - run: node profile/generate.mjs
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: generate commit message
        uses: mathiasvr/command-output@v2.0.0
        id: commit-msg
        with:
          run: |
            git diff profile/README.md | awk '
            BEGIN {
                added = "";
                removed = "";
            }

            /^\+ - / {
                split($3, a, "/");
                if (added != "") added = added ", ";
                added = added "`" a[1] "`";
            }

            /^- - / {
                split($3, b, "/");
                if (removed != "") removed = removed ", ";
                removed = removed "`" b[1] "`";
            }

            END {
                if (added != "") print "added " added;
                if (added != "" && removed != "") print "; ";
                if (removed != "") print "removed " removed;
            }' | tr -d '\n' && echo
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: '[profile] ${{ steps.commit-msg.outputs.stdout }}'
