name: 'update profile'

on:
  schedule:
    - cron: '55 * * * *'

permissions:
  contents: read

jobs:
  profile:
    name: 'generate profile contents'
    runs-on: 'ubuntu-latest'
    permissions:
      contents: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit
      - uses: actions/checkout@v3
      - uses: ljharb/actions/node/install@main
      - run: node profile/generate.mjs
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: '[profile] node profile/generate.mjs'
